In [1]:
import numpy as np
import pandas as pd
import math
from scipy.stats import poisson
import time
import matplotlib.pyplot as plt
import plotly.express as px


## Functions

In [2]:
I = 48  # Number of intervals
d = 5  # length of interval
x = np.random.choice(5, I)
N = sum(x)
precision = 0.9999
beta = 9  # Average service time for a patient
no_show = 0 # Fraction of scheduled patients not showing up
eind = 0
alpha_I = 0.2
alpha_T = 0.4  # patient doctor centric slider
alpha_W = 0.4

print(N)

95


In [3]:
def calcExponentialLimit(mu):
    return int(max(mu+4*mu**0.5, 100))

In [4]:
def binomCoeff(k, i):
  return math.factorial(k) / (math.factorial(k - i) * math.factorial(i))


def binomPMF(k, i, m, add_v, no_show):
  return binomCoeff(k, m) * add_v[m][i] * (1 - no_show)**m * no_show**(k-m)

In [5]:
# Distribution to calculate service time of patients
#	p[i]= probability of serving the patient in i mins given that
#	the average service time is beta.
def calculate_p(beta, size, precision=0.9999):  # Poisson distribution
    k = 0
    p = []

    while sum(p) < precision:  # fill accurate values up to precision limit
        p.append(poisson.pmf(k, beta))
        k += 1

    while len(p) < size:  # fill the rest of the values with 0
        p.append(0)
    return p, k

##########
## TEST ##
##########

probS = calcExponentialLimit(beta*N)+1
print(probS)
calculate_p(beta, probS, precision)


972


([0.00012340980408667956,
  0.0011106882367801166,
  0.004998097065510523,
  0.014994291196531574,
  0.033737155192196056,
  0.06072687934595293,
  0.09109031901892926,
  0.1171161244529091,
  0.13175564000952278,
  0.13175564000952278,
  0.11858007600857066,
  0.09702006218883041,
  0.0727650466416229,
  0.050375801521123684,
  0.03238444383500792,
  0.01943066630100472,
  0.010929749794315179,
  0.005786338126402172,
  0.0028931690632010803,
  0.0013704485036215655,
  0.0006167018266297063,
  0.0002643007828413016,
  0.00010812304752598687,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
 

In [6]:
def calculate_v(p, beta, precision, precision_limit, N, d, no_show=0):
  count = precision_limit
  limit = calcExponentialLimit(beta*N) + 1
  v = np.zeros((N+1, limit+d))
  add_v = np.zeros((N+1, limit+d))

  add_v[0][0] = 1
  for k in range(1, N+1):
    limit = calcExponentialLimit(beta*k)
    i = 0
    sum_v = 0
    while sum_v < precision and i <= limit:
      z = 0
      while z <= count:
        add_v[k][i] += p[z] * add_v[k-1][i-z]
        z += 1
      sum_v += add_v[k][i]
      i += 1

  for k in range(N+1):
    i = 0
    sum_v = 0
    while sum_v < precision and i <= limit:
      for m in range(k+1):
        v[k][i] += binomPMF(k, i, m, add_v, no_show)
      sum_v += v[k][i]
      i += 1

  return v, limit

##########
## TEST ##
##########

p, precision_limit = calculate_p(beta, probS, precision)
calculate_v(p, beta, precision, precision_limit, N, d, no_show)


(array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [1.23409804e-04, 1.11068824e-03, 4.99809707e-03, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [1.52299797e-08, 2.74139635e-07, 2.46725672e-06, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        ...,
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [9.57342617e-08, 4.87276183e-08, 2.35318937e-08, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]),
 971)

In [7]:
def calculateProbabilities(x, precision, limit, v, I, d):
  p_plus = np.zeros((I+1, limit+d+1))
  p_min = np.zeros((I+1, limit+d+1))

  # Constraint 1
  p_min[0][0] = 1

  # Constraint 2
  sum_p = 0
  i = 0
  while sum_p < precision and i <= limit:
    p_plus[0][i] = v[x[0]][i]
    sum_p += p_plus[0][i]
    i += 1

  for t in range(1, I+1):  # calculate p_min and p_plus iteratively
    # Constraint 3
    for k in range(d+1):
      # probability of amount of work = 0 just before the start of t equals the cummulative probablity of amount of work less or equal to duration of the interval just at the start of the previous interval, t-1
      p_min[t][0] += p_plus[t-1][k]
    # Constraint 4
    for i in range(1, limit+1):

      # probability of amount of work = i just before the start of interval t equals the probablity of amount of work exceeding the duration of the interval by i just at the start of the previous interval, t-1
      p_min[t][i] = p_plus[t-1][i+d]

    # Constraint 5
    if t != I:  # I or I+1
      for i in range(limit+1):
        for j in range(i+1):
          p_plus[t][i] += p_min[t][j] * v[x[t]][i-j]

  return p_min, limit

##########
## TEST ##
##########

v, limit = calculate_v(p, beta, precision, precision_limit, N, d, no_show)
p_min, limit = calculateProbabilities(x, precision, limit, v, I, d)


In [8]:
def calcTardiness(p_min, limit, I):
  tardiness = 0
  # print(p_min[I])
  for k in range(limit):
    tardiness += k * p_min[I][k]  # I+1
  return tardiness


def calcIdletime(I, d, tardiness, N, no_show, beta):
  return (I * d) + tardiness - (N * (1 - no_show) * beta)  # I-1?


def calcWaitingtime(p_min, x, p, limit, I, N):
  w = np.zeros((I+1, N+1, limit+1))
  waitingtime = 0

  for t in range(0, I):
    if x[t] > 0:
      for k in range(limit):
        w[t][0][k] = p_min[t][k]
    if x[t] > 1:
      for i in range(1, x[t]+1):
        for k in range(limit+1):
          for j in range(k+1):
            w[t][i][k] += w[t][i-1][j] * p[k-j]

  for t in range(0, I):
    for i in range(0, x[t]):
      for k in range(limit+1):
        waitingtime += w[t][i][k] * k

  waitingtime /= N
  return waitingtime

##########
## TEST ##
##########

calcWaitingtime(p_min, x, p, limit, I, N)


318.20553977521774

In [9]:
def calcFracExcess(p_min, I):
  fracExcess = 0
  t = I+1
  for j in range(1, len(p_min[t])):
    fracExcess += p_min[t][j]
  fracExcess *= 100
  return fracExcess


##########
## TEST ##
##########

# calcFracExcess(p_min, I)


<div>
<img src="https://github.com/witusj/obp/blob/master/images/fitness2.png?raw=true" width="450">
<img src="https://github.com/witusj/obp/blob/master/images/fitness.png?raw=true" width="450">
</div>

In [10]:
def calcFitness(x, beta, precision, limit, v, N, no_show, I, d, eind, alpha_W, alpha_I, alpha_T):
  tic = time.perf_counter()
  p_min, limit = calculateProbabilities(x, precision, limit, v, I, d)
  toc = time.perf_counter()
  probT = toc-tic

  # Tardiness calcs
  tic = time.perf_counter()
  tardiness = calcTardiness(p_min, limit, I)
  toc = time.perf_counter()
  tardT = toc-tic

  # Idle time calcs new array of given shape and type, filled with zeros.
  tic = time.perf_counter()
  idletime = calcIdletime(I, d, tardiness, N, no_show, beta)
  toc = time.perf_counter()
  idletimeT = toc-tic

  # Waiting time calcs
  tic = time.perf_counter()
  waitingtime = calcWaitingtime(p_min, x, p, limit, I, N)
  toc = time.perf_counter()
  waitingtimeT = toc-tic

  objVal = alpha_W*waitingtime + alpha_I*idletime + alpha_T*tardiness

  print(f"Schedule: {x},\nN: {sum(x)},\nObjective value: {objVal},\nProb calculation time: {probT:.6f} sec,\nWaiting time (timer): {waitingtime} ({waitingtimeT:.6f} sec),\nIdle time (timer): {idletime} ({idletimeT:.6f} sec),\nTardiness (timer): {tardiness} ({tardT:.6f} sec)\n")

  # Collect into a dictionary
  results = {'p_min': p_min, 'waitingTime': waitingtime,
            'idleTime': idletime, 'tardiness': tardiness, 'objVal': objVal}

  if eind == 1:
    fracExcess = calcFracExcess(p_min, I)
    results['fracExcess'] = fracExcess

  return results

##########
## TEST ##
##########


p, precision_limit = calculate_p(beta, probS, precision)
v, limit = calculate_v(p, beta, precision, precision_limit, N, d, no_show)



results = calcFitness(x, beta, precision, limit, v, N, no_show,
                  I, d, eind, alpha_W, alpha_I, alpha_T)
results


Schedule: [2 3 1 4 4 1 2 1 4 3 3 4 0 4 3 0 3 4 2 3 2 0 4 0 0 4 1 3 1 1 3 0 0 4 2 2 2
 0 0 0 2 1 4 1 2 3 1 1],
N: 95,
Objective value: 370.89184500144233,
Prob calculation time: 18.887867 sec,
Waiting time (timer): 318.20553977521774 (40.318315 sec),
Idle time (timer): -3.983951514407977 (0.000002 sec),
Tardiness (timer): 611.016048485592 (0.000352 sec)



{'p_min': array([[1.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [3.23993451e-004, 7.19452059e-004, 1.85001958e-003, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [1.39754723e-010, 5.98532450e-010, 2.64341098e-009, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        ...,
        [3.65123342e-138, 1.87360844e-137, 1.00038207e-136, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [1.05782619e-137, 3.90517341e-137, 1.70976523e-136, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [1.64924586e-137, 5.26805164e-137, 2.10394268e-136, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000]]),
 'waitingTime': 318.20553977521774,
 'idleTime': -3.983951514407977,
 'tardiness': 611.016048485592,
 'objVal': 370.89184500144233}

In [11]:
def createDist(arr, reverse=False):
    minX, maxX = arr.min(), arr.max()
    minY, maxY = 0, 1
    if(reverse):
        minY, maxY = maxY, minY
    # Scale to values between 0, 1 and make total sum equal to 1
    arrScaled = np.interp(arr, (minX, maxX), (minY, maxY))
    arrNorm = [x / arrScaled.sum() for x in arrScaled]
    return(arrNorm)
    

##########
## TEST ##
##########

arr = np.random.choice(10, 5)
dist1 = createDist(arr)
dist2 = createDist(arr, reverse=True)
arr, dist1, sum(dist1), dist2, sum(dist2)


(array([6, 3, 7, 4, 6]),
 [0.2727272727272727,
  0.0,
  0.36363636363636365,
  0.09090909090909091,
  0.2727272727272727],
 1.0,
 [0.1111111111111111,
  0.4444444444444444,
  0.0,
  0.3333333333333333,
  0.1111111111111111],
 1.0)

<div>
<img src="https://github.com/witusj/obp/blob/master/images/crossover.png?raw=true" width="450">
<img src="https://github.com/witusj/obp/blob/master/images/crossover2.png?raw=true" width="450">
</div>

In [12]:
## OLD
def crossover(parent1, parent2, nSwaps):
    child1 = parent1.copy()
    child2 = parent2.copy()
    
    I = len(child1)
    
    # Calculate distribution for choosing intervals that will swap patients
    # The distribution is the normalized schedule. Intervals with zero patients will never be selected.
    # norm1 = sum(child1)
    # p1 = child1 / norm1
    p1 = createDist(child1)
    
    # The number of swaps should not exceed the maximum number of patients in any interval. Otherwise it might happen that the number of patients that are transfered exceeds availability, resulting in a negative amount.
    max1 = int(max(child1))
    max2 = int(max(child2))
    nSwaps = min(nSwaps, max1, max2)
    
    # Swap patients parent1 to parent 2
    i = np.random.choice(I, nSwaps, p=p1)
    for i in i:
        child1[i] += -1
        child2[i] += 1
    
    # Swap patients parent2 to parent 1
    # norm2 = sum(child2)
    # p2 = child2 / norm2
    p2 = createDist(child2)
    
    j = np.random.choice(I, nSwaps, p=p2)
    for j in j:
        child1[j] += 1
        child2[j] += -1
    return(child1, child2)

##########
## TEST ##
##########


parent1 = np.random.choice(5, I)
parent2 = np.random.choice(5, I)

print(parent1, parent2)
nSwaps = 3
children = crossover(parent1, parent2, nSwaps)
children


[0 3 1 4 1 0 4 0 1 2 3 4 3 0 3 0 3 1 0 3 1 0 4 0 0 3 2 0 1 1 1 0 1 1 2 0 2
 1 4 1 0 4 1 1 0 0 4 1] [3 3 4 0 3 3 1 2 4 4 0 1 0 0 4 2 4 3 1 0 0 1 2 0 4 1 2 3 1 2 4 3 2 4 1 3 3
 0 0 4 4 3 0 4 1 4 2 2]


(array([0, 3, 1, 4, 1, 0, 4, 0, 2, 2, 3, 4, 3, 0, 3, 0, 3, 1, 0, 3, 1, 0,
        3, 0, 0, 3, 2, 0, 1, 1, 1, 1, 1, 1, 2, 0, 2, 1, 4, 1, 0, 5, 0, 0,
        0, 0, 4, 1]),
 array([3, 3, 4, 0, 3, 3, 1, 2, 3, 4, 0, 1, 0, 0, 4, 2, 4, 3, 1, 0, 0, 1,
        3, 0, 4, 1, 2, 3, 1, 2, 4, 2, 2, 4, 1, 3, 3, 0, 0, 4, 4, 2, 1, 5,
        1, 4, 2, 2]))

In [13]:
def crossover(parent1, parent2, nSwaps):
    child1 = parent1.copy()
    child2 = parent2.copy()
    
    I = len(child1)
    
    # Calculate distribution for choosing intervals that will swap patients
    # The distribution is the normalized schedule. Intervals with zero patients will never be selected.
    p1 = createDist(child1)
    
    # Swap patients parent1 to parent 2
    n1 = nSwaps
    while(n1 > 0):
        i = np.random.choice(I, 1, p=p1)
        child1[i] += -1
        child2[i] += 1
        if(child1[i] == 0):
            p1 = createDist(child1) # If the number of patients in interval i reaches zero, this interval should not be selected again.
        n1 -= 1
    
    # Swap patients parent2 to parent 1
    p2 = createDist(child2)
    
    n2 = nSwaps
    while(n2 > 0):
        i = np.random.choice(I, 1, p=p2)
        child2[i] += -1
        child1[i] += 1
        if(child2[i] == 0):
            p2 = createDist(child2)
        n2 -= 1
        
    return(child1, child2)

##########
## TEST ##
##########

testI = 10
parent1 = np.random.choice(5, testI)
parent2 = np.random.choice(5, testI)

print(parent1, parent2)
nSwaps = 3
children = crossover(parent1, parent2, nSwaps)
children


[3 3 1 3 2 0 2 4 2 3] [0 3 1 4 0 1 0 3 4 0]


(array([3, 3, 1, 1, 2, 0, 2, 5, 3, 3]), array([0, 3, 1, 6, 0, 1, 0, 2, 3, 0]))


<div>
    <img src="https://github.com/witusj/obp/blob/master/images/mutation.png?raw=true" width="450">
    <img src="https://github.com/witusj/obp/blob/master/images/mutation1.png?raw=true" width="450">
</div>

In [14]:
def mutate(child, rate):
    if np.random.rand() < rate:
        x = len(child)
        i, j = np.random.choice(x, 2, replace=False).astype(int)
        a, b = child[i], child[j]
        child[i], child[j] = b, a
    return(child)

##########
## TEST ##
##########

child = children[0].copy()
print(child)
child = mutate(child, 1)
print(child)


[3 3 1 1 2 0 2 5 3 3]
[3 3 1 1 5 0 2 2 3 3]


## Classes

#### Suggesties: [get / set methods](https://www.geeksforgeeks.org/getter-and-setter-in-python/) voor parameters / met tests / nuttig voor optimaliseren hyper parameters, bv mbv bayesian stats

Create a data object to store and generate initial data.

In [15]:
class Data:
    def __init__(self, I=10, N=12, d=5, popSize=5, beta=9, precision=0.9999, no_show=0, eind=0, alpha_I=0.2, alpha_T=0.3, alpha_W=0.5, nSwaps=4, mutationRate=0.1):
        self.I = I
        self.N = N
        self.d = d
        self.popSize = popSize
        self.beta = beta
        self.precision = precision
        self.no_show = no_show
        self.probSize = calcExponentialLimit(self.beta*self.N)+1
        self.p, self.precision_limit = self.__calculate_p()
        self.v, self.limit = self.__calculate_v()
        self.eind = eind
        self.alpha_I, self.alpha_T, self.alpha_W = alpha_I, alpha_T, alpha_W
        self.nSwaps, self.mutationRate = nSwaps, mutationRate
    
    def get_initial_data(self): return np.array((self.I, self.N, self.d, self.beta, self.popSize, self.eind, self.alpha_I, self.alpha_T, self.alpha_W, self.nSwaps, self.mutationRate),
                                                dtype={'names': ('I', 'N', 'd', 'beta', 'popSize', 'eind', 'alpha_I', 'alpha_T', 'alpha_W', 'nSwaps', 'mutationRate'),
                                                'formats': ('i4', 'i4', 'i4', 'i4', 'i4', 'i4', 'f8', 'f8', 'f8', 'i4', 'f8')})

    def get_prob_data(self): return np.array((self.precision, self.no_show, self.probSize, self.precision_limit, self.limit),
                                                dtype={'names': ('precision', 'no_show', 'probSize', 'precision_limit', 'limit'),
                                                'formats': ('f8', 'f8', 'i4', 'f8', 'i4')})

    def calculate_p(self):  return calculate_p(self.beta, self.probSize, self.precision)
    __calculate_p = calculate_p
    
    def calculate_v(self): return calculate_v(self.p, self.beta, self.precision, self.precision_limit, self.N, self.d, self.no_show)
    __calculate_v = calculate_v
    

##########
## TEST ##
##########

newDataObject = Data(I, N)
initData = newDataObject.get_initial_data()
initData[['N', 'popSize']]


array((95, 5),
      dtype={'names': ['N', 'popSize'], 'formats': ['<i4', '<i4'], 'offsets': [4, 16], 'itemsize': 60})

<img src="https://github.com/witusj/obp/blob/master/images/population.png?raw=true" width="600">

Create a random individual. An individual is in this case one schedule.

In [16]:
class Schedule:
    def __init__(self, dataObject):
        self.I = dataObject.get_initial_data()['I']  # Number of intervals
        self.N = dataObject.get_initial_data()['N']  # Number of patients
        self.x = np.zeros(self.I).astype(int)# Empty schedule

    def create_random_schedule(self):
        for i in range(self.N):
            i = np.random.choice(self.I, 1)  # Interval ID
            self.x[i] = self.x[i] + 1
    def get_schedule(self): return(self.x)
    def print_schedule(self): print(self.x)


##########
## TEST ##
##########

dataObject = Data(I=I, N=N, d=d)
scheduleObject = Schedule(dataObject)
scheduleObject.print_schedule()
scheduleObject.create_random_schedule()
schedule = scheduleObject.get_schedule()
schedule

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]


array([0, 2, 1, 1, 2, 3, 2, 0, 0, 1, 3, 3, 2, 5, 0, 2, 0, 0, 3, 2, 5, 3,
       2, 1, 9, 2, 3, 2, 1, 2, 3, 3, 0, 2, 1, 2, 3, 2, 1, 1, 1, 2, 3, 2,
       2, 0, 2, 3])

Create population of individuals

In [17]:
class Population:
    global bestRank
    bestRank = []
    def __init__(self, dataObject, individuals=None):
        self.dataObject = dataObject
        self.params = self.dataObject.get_initial_data()
        self.prob_params = self.dataObject.get_prob_data()
        self.p, self.v = self.dataObject.p, self.dataObject.v
        self.individuals = individuals
        if self.individuals == None: self.__create_new_individuals() 
        self.fitnessScores = []

    def create_new_individuals(self):
        self.individuals = []
        for i in range(self.params['popSize']):
            x = Schedule(self.dataObject)
            x.create_random_schedule()
            x = x.get_schedule()
            self.individuals.append(x)
            
    __create_new_individuals = create_new_individuals
    
    def get_individuals(self): return(self.individuals)
    
    def calc_fitness_scores(self):
            beta, N, I, d, eind, alpha_W, alpha_I, alpha_T = self.params[['beta', 'N', 'I', 'd', 'eind', 'alpha_W', 'alpha_I', 'alpha_T']].tolist()
            precision, limit, no_show = self.prob_params[['precision', 'limit', 'no_show']].tolist()
            self.fitnessScores = np.array([calcFitness(x, beta=beta, precision=precision, limit=limit, v=self.v, N=N, no_show=no_show, I=I, d=d, eind=eind, alpha_W=alpha_W, alpha_I=alpha_I, alpha_T=alpha_T)['objVal'] for x in self.individuals])
            
    def apply_crossover(self):
        newIndividuals = []
        nSwaps = self.params['nSwaps']*1 ## Times 1 because otherwise refers to memorypoint
        mutationRate = self.params['mutationRate']
        self.population_dist = createDist(self.fitnessScores, reverse=True)
        
        for i in range(self.params['popSize']):
            print(f'Crossover {i}')
            r1, r2 = np.random.choice(self.params['popSize'], 2, replace=False, p=self.population_dist)
            parent1, parent2 = self.individuals[r1], self.individuals[r2]
            child1, child2 = crossover(parent1, parent2, nSwaps)
            newIndividuals.append(mutate(child1, mutationRate))
            newIndividuals.append(mutate(child2, mutationRate))
            
        beta, N, I, d, eind, alpha_W, alpha_I, alpha_T = self.params[[
            'beta', 'N', 'I', 'd', 'eind', 'alpha_W', 'alpha_I', 'alpha_T']].tolist()
        precision, limit, no_show = self.prob_params[[
            'precision', 'limit', 'no_show']].tolist()
        self.fitnessScores = np.array([calcFitness(x, beta=beta, precision=precision, limit=limit, v=self.v, N=N, no_show=no_show,
                                            I=I, d=d, eind=eind, alpha_W=alpha_W, alpha_I=alpha_I, alpha_T=alpha_T)['objVal'] for x in newIndividuals])
        tempList = list(range(self.params['popSize']*2))
        zipped = list(zip(*sorted(zip(self.fitnessScores, tempList))))
        self.fitnessScores = np.array(list(zipped[0][:self.params['popSize']]))
        tempList = zipped[1][:self.params['popSize']]
        self.individuals = list(map(newIndividuals.__getitem__, tempList))
        bestRank.append([self.fitnessScores[0], self.individuals[0]])
        print(self.fitnessScores, '\n', self.individuals)


## Tests

In [18]:
##########
## TEST ##
##########

bestRank = []
dataObject = Data()
populationObject1 = Population(dataObject)
populationObject1.fitnessScores
populationObject1.calc_fitness_scores()
print(populationObject1.fitnessScores)


Schedule: [2 2 1 1 1 2 1 0 2 0],
N: 12,
Objective value: 33.1521862882858,
Prob calculation time: 0.112196 sec,
Waiting time (timer): 31.56243160396974 (0.092080 sec),
Idle time (timer): -0.05805902739814428 (0.000002 sec),
Tardiness (timer): 57.94194097260186 (0.000062 sec)

Schedule: [2 0 0 1 1 3 3 0 0 2],
N: 12,
Objective value: 30.564215451046064,
Prob calculation time: 0.086833 sec,
Waiting time (timer): 25.800210000617927 (0.110721 sec),
Idle time (timer): 0.5282209014741994 (0.000002 sec),
Tardiness (timer): 58.5282209014742 (0.000060 sec)

Schedule: [1 0 1 0 2 3 3 0 2 0],
N: 12,
Objective value: 32.84559445382523,
Prob calculation time: 0.091235 sec,
Waiting time (timer): 27.72939173876098 (0.110215 sec),
Idle time (timer): 3.1617971688894784 (0.000002 sec),
Tardiness (timer): 61.16179716888947 (0.000061 sec)

Schedule: [1 2 2 0 0 1 1 1 2 2],
N: 12,
Objective value: 30.109295748958914,
Prob calculation time: 0.086104 sec,
Waiting time (timer): 25.392366908913242 (0.087706 sec),

In [19]:
individuals2 = populationObject1.individuals.copy()
populationObject2 = Population(dataObject, individuals=individuals2)
print(populationObject1.individuals, '\n', populationObject2.individuals)

[array([2, 2, 1, 1, 1, 2, 1, 0, 2, 0]), array([2, 0, 0, 1, 1, 3, 3, 0, 0, 2]), array([1, 0, 1, 0, 2, 3, 3, 0, 2, 0]), array([1, 2, 2, 0, 0, 1, 1, 1, 2, 2]), array([0, 3, 0, 0, 1, 2, 0, 2, 1, 3])] 
 [array([2, 2, 1, 1, 1, 2, 1, 0, 2, 0]), array([2, 0, 0, 1, 1, 3, 3, 0, 0, 2]), array([1, 0, 1, 0, 2, 3, 3, 0, 2, 0]), array([1, 2, 2, 0, 0, 1, 1, 1, 2, 2]), array([0, 3, 0, 0, 1, 2, 0, 2, 1, 3])]


In [20]:
populationObject2.calc_fitness_scores()
populationObject2.apply_crossover()
populationObject2.individuals


Schedule: [2 2 1 1 1 2 1 0 2 0],
N: 12,
Objective value: 33.1521862882858,
Prob calculation time: 0.098553 sec,
Waiting time (timer): 31.56243160396974 (0.087055 sec),
Idle time (timer): -0.05805902739814428 (0.000002 sec),
Tardiness (timer): 57.94194097260186 (0.000059 sec)

Schedule: [2 0 0 1 1 3 3 0 0 2],
N: 12,
Objective value: 30.564215451046064,
Prob calculation time: 0.087072 sec,
Waiting time (timer): 25.800210000617927 (0.113535 sec),
Idle time (timer): 0.5282209014741994 (0.000002 sec),
Tardiness (timer): 58.5282209014742 (0.000055 sec)

Schedule: [1 0 1 0 2 3 3 0 2 0],
N: 12,
Objective value: 32.84559445382523,
Prob calculation time: 0.092365 sec,
Waiting time (timer): 27.72939173876098 (0.107461 sec),
Idle time (timer): 3.1617971688894784 (0.000002 sec),
Tardiness (timer): 61.16179716888947 (0.000061 sec)

Schedule: [1 2 2 0 0 1 1 1 2 2],
N: 12,
Objective value: 30.109295748958914,
Prob calculation time: 0.092768 sec,
Waiting time (timer): 25.392366908913242 (0.085831 sec),

[array([1, 0, 2, 0, 0, 1, 3, 1, 3, 1]),
 array([3, 1, 0, 1, 0, 2, 1, 0, 2, 2]),
 array([2, 0, 1, 1, 1, 3, 2, 0, 0, 2]),
 array([2, 0, 0, 1, 1, 4, 3, 0, 0, 1]),
 array([3, 0, 1, 1, 1, 1, 3, 0, 0, 2])]

In [21]:
# Initial population
bestRank = []
dataObject = Data()
populationZero = Population(dataObject)
populationZero.calc_fitness_scores()
individuals = populationZero.individuals.copy()
generations = 3

# Genetic algorithm loop
for i in range(generations):
    print(f'Generation: {i}')
    populationObject = Population(dataObject, individuals=individuals)
    populationObject.calc_fitness_scores()
    populationObject.apply_crossover()
    individuals = populationObject.individuals


Schedule: [1 2 0 3 1 0 1 2 1 1],
N: 12,
Objective value: 31.36238856241048,
Prob calculation time: 0.091478 sec,
Waiting time (timer): 27.894307509812588 (0.075848 sec),
Idle time (timer): 0.03046961500837142 (0.000002 sec),
Tardiness (timer): 58.030469615008364 (0.000060 sec)

Schedule: [0 2 0 3 1 0 1 2 2 1],
N: 12,
Objective value: 34.63332610067497,
Prob calculation time: 0.088676 sec,
Waiting time (timer): 29.502037009232794 (0.099728 sec),
Idle time (timer): 4.964615192117151 (0.000002 sec),
Tardiness (timer): 62.96461519211715 (0.000056 sec)

Schedule: [1 0 1 0 2 2 2 0 2 2],
N: 12,
Objective value: 31.38811021383182,
Prob calculation time: 0.098331 sec,
Waiting time (timer): 24.814423193497916 (0.111732 sec),
Idle time (timer): 3.161797234165732 (0.000002 sec),
Tardiness (timer): 61.161797234165725 (0.000062 sec)

Schedule: [1 1 1 1 2 2 2 1 0 1],
N: 12,
Objective value: 31.373184181542683,
Prob calculation time: 0.087690 sec,
Waiting time (timer): 27.903897903723887 (0.067854 sec

In [22]:

bestRankDF = pd.DataFrame(bestRank, columns=['Score', 'Schedule'])
bestRank
bestRankDF


Score                        Schedule
0  28.408087  [1, 1, 1, 0, 1, 0, 2, 1, 3, 2]
1  28.548955  [2, 1, 1, 0, 0, 0, 1, 1, 3, 3]
2  28.472317  [1, 1, 0, 1, 1, 0, 1, 3, 2, 2]

In [23]:
bestRank = []
precision = 0.9999
N = 24  # number of patients
beta = 9  # average service time for a patient
T = 4*60  # total time
d = 5  # interval size
I = int(T/d)  # number of intervals
no_show = 0
eind = 0
alpha_I = 0.2
alpha_T = 0.4  # patient doctor centric slider
alpha_W = 0.4
popSize = 10
generations = 5

# Initial population
dataObject = Data(N=N, beta=beta, d=d, I=I, no_show=no_show, eind=eind, alpha_I=alpha_I, alpha_T=alpha_T, alpha_W=alpha_W, popSize=popSize)
populationZero = Population(dataObject)
populationZero.calc_fitness_scores()
best_score = min(populationZero.fitnessScores)
score_list = [best_score]
individuals = populationZero.individuals.copy()
fitnessScores = populationZero.fitnessScores.copy()

# Genetic algorithm loop

for i in range(generations):
    print(f'Generation {i}')
    populationObject = Population(dataObject, individuals=individuals)
    populationObject.fitnessScores = fitnessScores
    populationObject.apply_crossover()
    best_score = min(populationObject.fitnessScores)
    score_list.append(best_score)
    individuals = populationObject.individuals.copy()
    fitnessScores = populationObject.fitnessScores.copy()


Schedule: [1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 1 1 0 1 0 0 2 1 0 0 0 0 0 2 2 1 0
 1 1 0 0 1 0 1 0 1 1 0],
N: 24,
Objective value: 24.017031383100274,
Prob calculation time: 1.527007 sec,
Waiting time (timer): 11.376435354285121 (0.227004 sec),
Idle time (timer): 48.44409540231038 (0.000002 sec),
Tardiness (timer): 24.44409540231037 (0.000197 sec)

Schedule: [0 2 2 0 0 0 1 0 0 0 0 0 1 0 1 0 2 0 1 1 0 0 0 0 0 0 1 0 2 0 0 1 2 0 3 0 1
 0 0 1 1 0 0 0 0 0 0 1],
N: 24,
Objective value: 16.53337214041592,
Prob calculation time: 1.533673 sec,
Waiting time (timer): 12.735612781893737 (0.471764 sec),
Idle time (timer): 35.06521171276404 (0.000002 sec),
Tardiness (timer): 11.065211712764041 (0.000107 sec)

Schedule: [0 0 0 0 0 2 1 0 1 0 0 1 0 1 0 1 1 0 2 0 0 2 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0
 1 0 0 2 1 0 1 1 0 2 0],
N: 24,
Objective value: 23.058514271425203,
Prob calculation time: 1.526950 sec,
Waiting time (timer): 9.55299614338836 (0.366728 sec),
Idle time (timer): 48.062193023449765 (0.00000

In [24]:
bestRankDF = pd.DataFrame(bestRank, columns=['Score', 'Schedule'])
bestRank
bestRankDF['Generation'] = bestRankDF.index.values
fig = px.line(bestRankDF, x='Generation', y='Score',hover_data=['Schedule'])
fig.update_traces(line_color='LimeGreen')
fig.show()
fileName = f'p{popSize}g{generations}n{nSwaps}.html'
fig.write_html(f'charts/{fileName}', include_plotlyjs="cdn")


In [25]:
bestRank = []
precision = 0.9999
N = 24  # number of patients
beta = 9  # average service time for a patient
T = 4*60  # total time
d = 5  # interval size
I = int(T/d)  # number of intervals
no_show = 0
eind = 0
alpha_I = 0.2
alpha_T = 0.4  # patient doctor centric slider
alpha_W = 0.4
popSize = 15
generations = 10

# Initial population
dataObject = Data(N=N, beta=beta, d=d, I=I, no_show=no_show, eind=eind,
                    alpha_I=alpha_I, alpha_T=alpha_T, alpha_W=alpha_W, popSize=popSize)
populationZero = Population(dataObject)
populationZero.calc_fitness_scores()
best_score = min(populationZero.fitnessScores)
score_list = [best_score]
individuals = populationZero.individuals.copy()
fitnessScores = populationZero.fitnessScores.copy()

# Genetic algorithm loop
score_list = []
for i in range(generations):
    print(f'Generation {i}')
    tic = time.perf_counter()
    populationObject = Population(dataObject, individuals=individuals)
    toc = time.perf_counter()
    objTime = toc - tic
    populationObject.fitnessScores = fitnessScores
    best_score = min(populationObject.fitnessScores)
    score_list.append(best_score)
    tic = time.perf_counter()
    populationObject.apply_crossover()
    toc = time.perf_counter()
    crossTime = toc - tic
    individuals = populationObject.individuals.copy()
    fitnessScores = populationObject.fitnessScores.copy()
    print(f'Population building time: : {objTime}\nCrossover time: {crossTime}\n')


Schedule: [0 0 0 1 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 2 1 2 1
 1 0 0 1 0 2 0 1 1 3 0],
N: 24,
Objective value: 52.13593010432948,
Prob calculation time: 1.638499 sec,
Waiting time (timer): 22.391235441219766 (0.390482 sec),
Idle time (timer): 87.9657265464026 (0.000002 sec),
Tardiness (timer): 63.96572654640262 (0.000110 sec)

Schedule: [1 1 0 1 1 0 1 0 1 0 0 0 1 1 0 2 0 1 0 1 2 1 0 1 0 1 0 1 1 0 0 0 1 1 0 0 0
 0 0 0 0 0 0 1 0 2 0 0],
N: 24,
Objective value: 12.550196458141524,
Prob calculation time: 1.596227 sec,
Waiting time (timer): 12.72139753989673 (0.237650 sec),
Idle time (timer): 28.43606240363806 (0.000002 sec),
Tardiness (timer): 4.436062403638047 (0.000108 sec)

Schedule: [0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 0 0 0 2 1 0 0 1 0 0 1 1 0 1 0 1 0 2 0 1
 1 0 1 0 0 1 0 1 0 1 0],
N: 24,
Objective value: 12.87428328287359,
Prob calculation time: 1.620122 sec,
Waiting time (timer): 7.015432121657743 (0.159184 sec),
Idle time (timer): 32.78018405701749 (0.000002 se

In [26]:
bestRankDF = pd.DataFrame(bestRank, columns=['Score', 'Schedule'])
bestRank
bestRankDF['Generation'] = bestRankDF.index.values
fig = px.line(bestRankDF, x='Generation', y='Score', hover_data=['Schedule'])
fig.update_traces(line_color='RoyalBlue')
fig.show()
fileName = f'p{popSize}g{generations}n{nSwaps}.html'
fig.write_html(f'charts/{fileName}', include_plotlyjs="cdn")


In [27]:
bestRank = []
precision = 0.9999
N = 24  # number of patients
beta = 9  # average service time for a patient
T = 4*60  # total time
d = 5  # interval size
I = int(T/d)  # number of intervals
no_show = 0
eind = 0
alpha_I = 0.2
alpha_T = 0.4  # patient doctor centric slider
alpha_W = 0.4
popSize = 15
generations = 20

# Initial population
dataObject = Data(N=N, beta=beta, d=d, I=I, no_show=no_show, eind=eind,
                    alpha_I=alpha_I, alpha_T=alpha_T, alpha_W=alpha_W, popSize=popSize)
populationZero = Population(dataObject)
populationZero.calc_fitness_scores()
best_score = min(populationZero.fitnessScores)
score_list = [best_score]
individuals = populationZero.individuals.copy()
fitnessScores = populationZero.fitnessScores.copy()

# Genetic algorithm loop
score_list = []
for i in range(generations):
    print(f'Generation {i}')
    tic = time.perf_counter()
    populationObject = Population(dataObject, individuals=individuals)
    toc = time.perf_counter()
    objTime = toc - tic
    populationObject.fitnessScores = fitnessScores
    best_score = min(populationObject.fitnessScores)
    score_list.append(best_score)
    tic = time.perf_counter()
    populationObject.apply_crossover()
    toc = time.perf_counter()
    crossTime = toc - tic
    individuals = populationObject.individuals.copy()
    fitnessScores = populationObject.fitnessScores.copy()
    print(f'Population building time: : {objTime}\nCrossover time: {crossTime}\n')


Schedule: [1 0 0 0 0 0 0 0 2 0 1 2 1 2 0 0 0 2 1 0 1 1 2 0 0 0 0 0 0 0 0 1 1 0 0 1 0
 0 0 1 1 0 0 0 1 1 0 1],
N: 24,
Objective value: 21.387067147364533,
Prob calculation time: 1.529372 sec,
Waiting time (timer): 22.446316479812722 (0.396059 sec),
Idle time (timer): 36.6809009257324 (0.000002 sec),
Tardiness (timer): 12.680900925732407 (0.000102 sec)

Schedule: [0 0 1 0 1 2 0 0 0 0 2 1 1 0 0 0 0 1 0 1 0 0 1 0 0 1 1 1 1 0 0 1 0 0 1 1 0
 0 0 2 0 2 0 1 0 1 0 0],
N: 24,
Objective value: 14.125652595339625,
Prob calculation time: 1.565062 sec,
Waiting time (timer): 7.782725630459975 (0.300854 sec),
Idle time (timer): 34.354270571926065 (0.000002 sec),
Tardiness (timer): 10.354270571926051 (0.000111 sec)

Schedule: [2 2 0 0 0 0 1 0 1 1 2 2 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 4 0 0 0
 0 0 0 0 0 1 0 1 0 1 0],
N: 24,
Objective value: 12.927270862765047,
Prob calculation time: 1.545050 sec,
Waiting time (timer): 17.54976799981633 (0.444932 sec),
Idle time (timer): 25.845606104730848 (0.000

In [28]:
bestRankDF = pd.DataFrame(bestRank, columns=['Score', 'Schedule'])
bestRank
bestRankDF['Generation'] = bestRankDF.index.values
fig = px.line(bestRankDF, x='Generation', y='Score', hover_data=['Schedule'])
fig.update_traces(line_color='Tomato')
fig.show()
fileName = f'p{popSize}g{generations}n{nSwaps}.html'
fig.write_html(f'charts/{fileName}', include_plotlyjs="cdn")


In [29]:
bestRank = []
precision = 0.9999
N = 24  # number of patients
beta = 9  # average service time for a patient
T = 4*60  # total time
d = 5  # interval size
I = int(T/d)  # number of intervals
no_show = 0
eind = 0
alpha_I = 0.2
alpha_T = 0.4  # patient doctor centric slider
alpha_W = 0.4
popSize = 10
generations = 5
nSwaps = 6

# Initial population
dataObject = Data(N=N, beta=beta, d=d, I=I, no_show=no_show, eind=eind, alpha_I=alpha_I, alpha_T=alpha_T, alpha_W=alpha_W, popSize=popSize, nSwaps=nSwaps)
populationZero = Population(dataObject)
populationZero.calc_fitness_scores()
best_score = min(populationZero.fitnessScores)
score_list = [best_score]
individuals = populationZero.individuals.copy()
fitnessScores = populationZero.fitnessScores.copy()

# Genetic algorithm loop

for i in range(generations):
    print(f'Generation {i}')
    populationObject = Population(dataObject, individuals=individuals)
    populationObject.fitnessScores = fitnessScores
    populationObject.apply_crossover()
    best_score = min(populationObject.fitnessScores)
    score_list.append(best_score)
    individuals = populationObject.individuals.copy()
    fitnessScores = populationObject.fitnessScores.copy()


Schedule: [0 1 0 0 0 1 0 2 0 2 0 1 1 1 0 1 0 0 0 1 1 2 1 0 0 0 2 0 0 0 0 0 1 0 0 0 1
 0 0 0 2 0 0 1 0 1 0 1],
N: 24,
Objective value: 15.287787496480462,
Prob calculation time: 1.855426 sec,
Waiting time (timer): 13.943389689024217 (0.465904 sec),
Idle time (timer): 32.18405270145129 (0.000003 sec),
Tardiness (timer): 8.18405270145129 (0.000126 sec)

Schedule: [0 1 0 0 1 0 0 2 2 0 0 0 0 2 0 1 0 1 0 1 0 0 0 0 1 2 1 0 1 0 0 1 0 0 0 0 1
 1 0 0 0 0 2 1 1 0 0 1],
N: 24,
Objective value: 17.9323366126443,
Prob calculation time: 1.827592 sec,
Waiting time (timer): 9.912702258469178 (0.459871 sec),
Idle time (timer): 39.27875951542771 (0.000002 sec),
Tardiness (timer): 15.27875951542772 (0.000131 sec)

Schedule: [1 0 0 1 0 2 2 0 0 0 0 1 2 0 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0 1 0 1 0 0 0 0 0
 0 0 1 2 1 0 0 1 0 3 0],
N: 24,
Objective value: 24.634957498879828,
Prob calculation time: 1.825356 sec,
Waiting time (timer): 8.800748231422437 (0.513236 sec),
Idle time (timer): 51.19109701051809 (0.000002 se

In [35]:
bestRankDF = pd.DataFrame(bestRank, columns=['Score', 'Schedule'])
bestRank
bestRankDF['Generation'] = bestRankDF.index.values
fig = px.line(bestRankDF, x='Generation', y='Score', hover_data=['Schedule'])
fig.update_traces(line_color='DarkOrange')
fig.show()
fileName = f'p{popSize}g{generations}n{nSwaps}.html'
fig.write_html(f'charts/fileName', include_plotlyjs="cdn")


In [31]:
bestRank = []
precision = 0.9999
N = 24  # number of patients
beta = 9  # average service time for a patient
T = 4*60  # total time
d = 5  # interval size
I = int(T/d)  # number of intervals
no_show = 0
eind = 0
alpha_I = 0.2
alpha_T = 0.4  # patient doctor centric slider
alpha_W = 0.4
popSize = 15
generations = 5
nSwaps = 6

# Initial population
dataObject = Data(N=N, beta=beta, d=d, I=I, no_show=no_show, eind=eind, alpha_I=alpha_I, alpha_T=alpha_T, alpha_W=alpha_W, popSize=popSize, nSwaps=nSwaps)
populationZero = Population(dataObject)
populationZero.calc_fitness_scores()
best_score = min(populationZero.fitnessScores)
score_list = [best_score]
individuals = populationZero.individuals.copy()
fitnessScores = populationZero.fitnessScores.copy()

# Genetic algorithm loop

for i in range(generations):
    print(f'Generation {i}')
    populationObject = Population(dataObject, individuals=individuals)
    populationObject.fitnessScores = fitnessScores
    populationObject.apply_crossover()
    best_score = min(populationObject.fitnessScores)
    score_list.append(best_score)
    individuals = populationObject.individuals.copy()
    fitnessScores = populationObject.fitnessScores.copy()


Schedule: [0 1 0 0 0 0 1 0 1 0 0 2 2 1 1 0 1 1 0 0 0 0 1 1 0 0 3 0 1 0 0 0 0 0 0 0 0
 0 1 0 0 2 0 0 2 1 0 1],
N: 24,
Objective value: 23.00961672112808,
Prob calculation time: 1.766489 sec,
Waiting time (timer): 15.38741678756571 (0.463775 sec),
Idle time (timer): 44.09108334350299 (0.000002 sec),
Tardiness (timer): 20.091083343502987 (0.000162 sec)

Schedule: [0 0 0 1 1 0 1 1 1 0 0 1 0 0 1 1 0 0 0 0 2 0 0 2 0 0 1 0 1 1 0 0 1 0 0 0 0
 2 1 0 2 0 0 0 1 1 1 0],
N: 24,
Objective value: 18.558815583806243,
Prob calculation time: 1.797491 sec,
Waiting time (timer): 8.21747859038594 (0.359704 sec),
Idle time (timer): 41.45304024608646 (0.000002 sec),
Tardiness (timer): 17.453040246086438 (0.000130 sec)

Schedule: [1 2 0 0 0 0 1 0 0 0 0 0 0 0 2 0 1 1 0 0 0 1 2 1 0 0 1 0 0 0 1 0 1 1 1 1 0
 0 1 1 0 0 0 0 0 0 2 2],
N: 24,
Objective value: 24.507765531455345,
Prob calculation time: 1.775114 sec,
Waiting time (timer): 9.405196010238344 (0.438337 sec),
Idle time (timer): 50.57614521226668 (0.000024 

In [36]:
bestRankDF = pd.DataFrame(bestRank, columns=['Score', 'Schedule'])
bestRank
bestRankDF['Generation'] = bestRankDF.index.values
fig = px.line(bestRankDF, x='Generation', y='Score', hover_data=['Schedule'])
fig.update_traces(line_color='DarkCyan')
fig.show()
fileName = f'p{popSize}g{generations}n{nSwaps}.html'
fig.write_html(f'charts/{fileName}', include_plotlyjs="cdn")
