In [1]:
import numpy as np

Create random individual

In [175]:
class Schedule:
    def __init__(self, I, N):
        self.I = I  # Number of intervals
        self.N = N  # Number of patients
        self.x = np.zeros(I) # Empty schedule

    def set_random_schedule(self):
        for i in range(self.N):
            i = np.random.choice(self.I, 1)  # Interval ID
            self.x[i] = self.x[i] + 1
    def get_schedule(self): return(self.x)
    def print_schedule(self): print(self.x)
        
I = 10  # Number of time slots
N = 8  # Number of patients
x = Schedule(I, N)
x.print_schedule()
x.set_random_schedule()
x.print_schedule()

y = Schedule(I, N)
y.set_random_schedule()
y = y.get_schedule()
y

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2. 0. 0. 1. 2. 0. 0. 1. 2. 0.]


array([0., 0., 2., 0., 0., 2., 2., 1., 1., 0.])

In [108]:
class Population:
    def __init__(self, size):
        self.size = size
        self.population = []
    def create_population(self):
        for i in range(self.size):
            x = Schedule
            self.population.append
            

array([1., 0., 0., 2., 1., 1., 1., 1., 0., 1.])