In [49]:
import numpy as np

Create random individual

In [50]:
class Schedule:
    def __init__(self, I, N):
        self.I = I  # Number of intervals
        self.N = N  # Number of patients
        self.x = np.zeros(self.I) # Empty schedule

    def create_random_schedule(self):
        for i in range(self.N):
            i = np.random.choice(self.I, 1)  # Interval ID
            self.x[i] = self.x[i] + 1
    def get_schedule(self): return(self.x)
    def print_schedule(self): print(self.x)
        
I = 10  # Number of time slots
N = 8  # Number of patients
scheduleObject = Schedule(I, N)
scheduleObject.print_schedule()
scheduleObject.create_random_schedule()
schedule = scheduleObject.get_schedule()
schedule


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 2., 0., 0., 2., 2., 0., 1., 1., 0.])

Create population of individuals

In [51]:
class Population:
    def __init__(self, I, N, size):
        self.I = I
        self.N = N
        self.size = size
        self.individuals = []
        self.__create_new_individuals()

    def create_new_individuals(self):
        for i in range(self.size):
            x = Schedule(self.I, self.N)
            x.create_random_schedule()
            x = x.get_schedule()
            self.individuals.append(x)
            
    __create_new_individuals = create_new_individuals
    
    def get_individuals(self): return(self.individuals)
    
            
size = 12
populationObject = Population(I, N, size)
populationObject.individuals

[array([1., 4., 0., 0., 0., 1., 0., 1., 0., 1.]),
 array([0., 1., 2., 0., 1., 2., 1., 0., 1., 0.]),
 array([1., 0., 1., 3., 0., 1., 0., 2., 0., 0.]),
 array([1., 0., 0., 0., 2., 2., 1., 1., 0., 1.]),
 array([0., 2., 2., 1., 0., 1., 0., 1., 0., 1.]),
 array([1., 0., 0., 1., 1., 1., 1., 0., 1., 2.]),
 array([1., 3., 0., 1., 3., 0., 0., 0., 0., 0.]),
 array([2., 0., 0., 0., 0., 1., 1., 3., 1., 0.]),
 array([1., 1., 1., 1., 0., 2., 0., 2., 0., 0.]),
 array([1., 0., 1., 1., 0., 3., 0., 1., 0., 1.]),
 array([1., 0., 3., 0., 2., 0., 0., 1., 0., 1.]),
 array([0., 2., 1., 1., 1., 0., 0., 2., 0., 1.])]

In [6]:
populationObject.I, populationObject.N, populationObject.size

(10, 8, 12)

In [54]:
def crossover(parent1, parent2, I, n):
    child1 = parent1.copy()
    child2 = parent2.copy()
    p1 = np.linalg.norm(child1)
    p2 = np.linalg.norm(child2)
    
    i = np.random.choice(I, n, p1)
    j = np.random.choice(I, n, p2)

    for i in i:
        if child1[i] > 0:
            child1[i] += -1
            child2[i] += 1

    for j in j:
        if child2[j] > 0:
            child1[j] += 1
            child2[j] += -1
    return(child1, child2)


population = populationObject.get_individuals()
parent1 = population[0]
parent2 = population[1]

print(parent1, parent2)
n = 4
children = crossover(parent1, parent2, I, n)
children


[1. 4. 0. 0. 0. 1. 0. 1. 0. 1.] [0. 1. 2. 0. 1. 2. 1. 0. 1. 0.]


(array([1., 3., 0., 0., 0., 1., 1., 1., 0., 1.]),
 array([0., 2., 2., 0., 1., 2., 0., 0., 1., 0.]))